name: Build TinyWall
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v2
      name: Checkout Code
     
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
     
    - name: Restore NuGet Packages
      run: nuget restore TinyWall.sln
 
    - name: Build Solution
      run: |
        msbuild.exe TinyWall.sln /p:platform="Any CPU" /p:configuration="Release"
        
    - name: Build Installer
      run: |
        msbuild.exe MsiSetup\MsiSetup.wixproj
